In [1]:
from sktime.datasets import load_from_tsfile
import os
import numpy as np

In [2]:
### get current path
from pathlib import Path
path = Path.cwd()
path

PosixPath('/Users/mojtabaaskarzadeh/Library/CloudStorage/GoogleDrive-ma00048@mix.wvu.edu/My Drive/1-time-series classification in manufacturing/Code')

In [3]:
path_dir = '/Users/mojtabaaskarzadeh/Library/CloudStorage/GoogleDrive-ma00048@mix.wvu.edu/My Drive/1-time-series classification in manufacturing/Datasets'

In [4]:
archive = 'HandMovementDirection'
print(archive)

HandMovementDirection


In [5]:
PATH = os.path.join(path_dir,archive)
PATH

'/Users/mojtabaaskarzadeh/Library/CloudStorage/GoogleDrive-ma00048@mix.wvu.edu/My Drive/1-time-series classification in manufacturing/Datasets/HandMovementDirection'

In [6]:
X_train, y_train = load_from_tsfile(os.path.join(PATH, f"{archive}_TRAIN.ts"), return_data_type="numpy3d")
X_test, y_test = load_from_tsfile(os.path.join(PATH, f"{archive}_TEST.ts"), return_data_type="numpy3d")
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((160, 10, 400), (160,), (74, 10, 400), (74,))

In [7]:
ts = np.concatenate((X_train, X_test), axis=0)
print(f"\n The dataset shape is:{ts.shape}")
print(f"\n The number of data samples (N) is:{ts.shape[0]}")
print(f"\n The number of TS length (T) is:{ts.shape[1]}")
print(f"\n The number of TS dimention (M) is:{ts.shape[2]}")


 The dataset shape is:(234, 10, 400)

 The number of data samples (N) is:234

 The number of TS length (T) is:10

 The number of TS dimention (M) is:400


In [8]:
import sktime
import os
import numpy as np
import argparse
import time

In [9]:
## Classification
from sktime.classification.dictionary_based import MUSE
from sktime.classification.dictionary_based import WEASEL


t_total = time.time() ##Start timing

if ts.shape[2] == 1:
    print('Univariate Time-series. Using WEASEL')
    classifier = WEASEL(n_jobs=1, window_inc=4)
else:
    print('Multivariate Time-series. Using MUSE')
    classifier = MUSE(alphabet_size=2, n_jobs=-1, use_first_order_differences=True)

classifier.fit(X_train, y_train)

print("\n The classifier is fitted")
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report,f1_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))

print(" Finished!")
F1 = f1_score(y_test, y_pred, average='macro')
print(f"the f1 score is:{F1}")

print("Total time elapsed: {:.4f}s".format(time.time() - t_total))

Multivariate Time-series. Using MUSE


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  warnings.warn(



 The classifier is fitted
[[ 4  3  3  5]
 [ 9 10  4  7]
 [ 4  5  5  1]
 [ 2  3  2  7]]
              precision    recall  f1-score   support

    backward       0.21      0.27      0.24        15
     forward       0.48      0.33      0.39        30
        left       0.36      0.33      0.34        15
       right       0.35      0.50      0.41        14

    accuracy                           0.35        74
   macro avg       0.35      0.36      0.35        74
weighted avg       0.37      0.35      0.35        74

 Finished!
the f1 score is:0.3460108181203516
Total time elapsed: 60.7542s
